name: UnitTest

on:
  push:
    branches:
      - main
      - feature*

jobs:
  laravel_test:
    name: phpunit test
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0.19
        ports:
          - 3306:3306
        options: --health-cmd "mysqladmin ping -h localhost" --health-interval 20s --health-timeout 10s --health-retries 10
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.DB_DATABASE }}

    env:
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: ${{ secrets.DB_DATABASE }}
      DB_USERNAME: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
      - uses: actions/checkout@v2
      - name: cache vendor
        id: cache
        uses: actions/cache@v1
        with:
          path: ./vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: composer install
        if: steps.cache.outputs.cache-hit != 'true'
        run: composer install -n --prefer-dist
        working-directory: ./src
      - name: composer dump autoload
        run: composer dump-autoload
        working-directory: ./src
      - name: cache clear
        run: php artisan config:clear
        working-directory: ./src
      - name: generate key
        run: php artisan key:generate --env=testing
        working-directory: ./src
      # - name: migrate
      #   run: php artisan migrate --no-interaction 
      #   working-directory: ./src
      - name: unit test
        run: ./vendor/bin/phpunit